### ISSUE TITLE
is not currently in the FragmentManager

### ISSUE THREAD

**Issue by iamkurtgoz** [JetradarMobile/android-multibackstack#10]
Hello, I use 5 fragments. each fragmentte back stack works, but when you go back to the previous screen, the data disappears and the screen refreshes. Do you have a solution? It does not look like the old page as in Instagram.

@johnkil

**Comment by johnkil** [comment]
To prevent a refresh, you must save the current state and restore when you return to the screen.

**Comment by iamkurtgoz** [comment]
@johnkil The problem is getting solved too. But as you said, I solved it by taking it back. Thank you so much.

And I have one more question. Are you going to send a library update that gives non-serious errors when opening the application?

**Comment by johnkil** [comment]
What do you mean?
