### ISSUE TITLE
Can't change inactive color

### ISSUE THREAD

**Issue by Hary25** [JetradarMobile/android-multibackstack#3]
i cant change inactive color on tab, anyone help?
![341969](https://cloud.githubusercontent.com/assets/20138245/17467099/c5b3c3e8-5d44-11e6-80fa-dafd115ae573.jpg)

**Comment by johnkil** [comment]
Use attributes: bnbActiveColor, bnbInactiveColor, bnbBackgroundColor Value: Color value or resource

https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations#3-colors
