### ISSUE TITLE
Restore state of fragment on pop

### ISSUE THREAD

**Issue by PareshP2507** [JetradarMobile/android-multibackstack#5]
So, the problem is each fragment is recreated after poping up from backstack.
Here is what I've used for pushing a fragment

`((HomeActivity) context).showFragment(LikesFragment.newInstance(b), true);`

**Comment by johnkil** [comment]
@Wizard250793 Now there is a feature implementation 😬   I thought about the implementation of something like `FragmentPagerAdapter` or `FragmentStatePagerAdapter`. Maybe you have ideas on this issue?

**Comment by PareshP2507** [comment]
@johnkil I'm not sure I understood your comment. 
So basically,
I'm pushing Fragment `A`on stack using `showFragment(fragment, true)` method. Again I pushed Fragment `B` by clicking on the element of `A`. By `true` I'm telling to add the fragment in `backstack`, this works. But the problem is, When I pop the fragment `B`(which is what`OnBackPressed()` is doing) ,  Fragment `A` is recreated.

What if I want to restore the state of fragment?? How do I achieve that?
This is the snippet of Fragment `A`'s `onCreateView()`,

```
private View mainView;
@Nullable
@Override
 public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        if (mainView == null) {

            mainView = inflater.inflate(R.layout.frag_home, container, false);
            bindViews(mainView);
            setupLayout();
        }

        return mainView;
 }
```

mainView is always returned null, while coming back to Fragment `A`, while `savedInstanceState`is having some values.

**Comment by johnkil** [comment]
Hi @Wizard250793 
Yes, Fragment recreated anew, and is restored arguments of the previous saved state. See https://github.com/JetradarMobile/multibackstack/blob/master/multibackstack/src/main/java/com/jetradar/multibackstack/BackStackEntry.java#L51
